// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1vM9pf7DGm2-zWavzNgwnZtxL0ZnlK0',
    appId: '1:457374277759:web:cdccd45e055d820f861f4a',
    messagingSenderId: '457374277759',
    projectId: 'unlock-19038',
    authDomain: 'unlock-19038.firebaseapp.com',
    storageBucket: 'unlock-19038.appspot.com',
    measurementId: 'G-7TM23L6NG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmxa3V7owijBPSb_DS2kRPespi7Y4g_yk',
    appId: '1:457374277759:android:6aae572296d2f946861f4a',
    messagingSenderId: '457374277759',
    projectId: 'unlock-19038',
    storageBucket: 'unlock-19038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtSICkOjnNvRlujLcfnLVMV4VTwQMbVG4',
    appId: '1:457374277759:ios:befbd0f6b90addcd861f4a',
    messagingSenderId: '457374277759',
    projectId: 'unlock-19038',
    storageBucket: 'unlock-19038.appspot.com',
    iosBundleId: 'com.example.unlock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtSICkOjnNvRlujLcfnLVMV4VTwQMbVG4',
    appId: '1:457374277759:ios:7dccde3bf9730ecf861f4a',
    messagingSenderId: '457374277759',
    projectId: 'unlock-19038',
    storageBucket: 'unlock-19038.appspot.com',
    iosBundleId: 'com.example.unlock.RunnerTests',
  );
}
